### ISSUE TITLE
Feature Request: Single Subscription for Small-Enterprise model

### ISSUE THREAD

**Issue by richardf5** [Azure/ALZ-PowerShell-Module#154] opened 2024-05-06 05:19 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Is your feature request related to a problem?**

Yes. 

**Describe the solution you'd like**

We have many customers who want the 'small enterprise' model whereby the Management, Connectivity and Identity subscription are all in one. This includes our small/mid-market customers.

Their I.T. is simply not that distributed or separated enough to warrant splitting this function up into three separate Subscriptions.

This is currently possible when using the Azure Landing Zone Accelerator Wizard. Under 'Azure Core Setup' you can select either 'Dedicated (recommended)' or 'Single'.

Please see here for more information: https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/treyresearch/README.md

**Additional context**
I've tried to find a decent way to do this with the Enterprise Scale Terraform Module. Hoping you have better insight and skills :-)

**Comment by jtracey93** [comment] 2024-09-03 16:06
Yeah i think this is still a TBC but you can close either this one or https://github.com/Azure/ALZ-PowerShell-Module/issues/78 as they are the same thing - @jaredfholgate

**Comment by jaredfholgate** [comment] 2024-09-04 11:38
closing as a duplicate of #78

**Closed by jaredfholgate** 2024-09-04 11:38 UTC
Labels: Needs: Attention :wave:, Status: Blocked :brick:, Type: Duplicate :palms_up_together:, Type: Enhancement :sparkles:, Area: Bootstrap Modules :boot:, IaC: Terraform, IaC: Bicep, Module: Bootstrap
